behaviors:
  JumperAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 51200
      learning_rate: 3.0e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 2000000
    time_horizon: 128
    summary_freq: 10000
    checkpoint_interval: 500000
    keep_checkpoints: 5